### PANDAS

In [1]:
import pandas as pd

In [2]:
cd "C:\Users\Karthick\Desktop\ML class\Simple_Linear_Regression"

C:\Users\Karthick\Desktop\ML class\Simple_Linear_Regression


In [3]:
df = pd.read_csv("Marks_data.csv")

In [4]:
df.shape

(30, 4)

In [5]:
df.head(3)

Sleep_hours How_much_did_he_eat  Hours_of_study  Exam_score
0           30                High              24          68
1           35                High              24          73
2           20              Medium              20          65

In [6]:
df.How_much_did_he_eat [df.Exam_score > 70]

1       High
4        Low
5        Low
11      High
12    Medium
13       Low
14    Medium
29       Low
Name: How_much_did_he_eat, dtype: object

In [7]:
df.Exam_score.mean() # MAX, MIN

57.4

In [8]:
df.describe()

Sleep_hours  Hours_of_study  Exam_score
count    30.000000       30.000000   30.000000
mean     37.633333       19.166667   57.400000
std       9.099008        6.203911   18.488766
min      20.000000        5.000000   10.000000
25%      33.250000       14.250000   45.000000
50%      37.500000       19.000000   55.000000
75%      42.000000       23.750000   71.000000
max      60.000000       34.000000  107.000000

________________
________________

### NUMPY

In [9]:
import numpy as np

In [10]:
l = [1,2,3]
a = np.array([1,2,3])
b = np.array([4,5,6])

In [11]:
l+b

array([5, 7, 9])

In [12]:
a+b  #a*b

array([5, 7, 9])

In [13]:
2*l

[1, 2, 3, 1, 2, 3]

In [14]:
2*a # a**2

array([2, 4, 6])

In [15]:
np.sqrt(a) # np.exp(a) np.log(a)

array([1.        , 1.41421356, 1.73205081])

In [16]:
np.dot(a,b)  

32

In [17]:
mat = np.array([[1,2,3] , [4,5,6]])
mat.shape

(2, 3)

In [18]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
G = np.zeros((10,10)) #np.ones np.random.random #np.random.randn(10,10)  G.mean() G.var()

In [20]:
mat.T*mat.T # mat.T.dot(mat)

array([[ 1, 16],
       [ 4, 25],
       [ 9, 36]])

________________

## Other useful numpy functions
_____________
##### np.linalg.inv(A)          
##### np.linalg.det(A)          
##### np.diag(A)        
##### np.diag(1,2)
##### np.cov(A)
##### np.eig(A)